[PreloadAssets]
; Primitive meshes
+Paths=/Content/Mesh/Primitive/cone.obj
+Paths=/Content/Mesh/Primitive/cube.obj
+Paths=/Content/Mesh/Primitive/cylinder.obj
+Paths=/Content/Mesh/Primitive/quad.obj
+Paths=/Content/Mesh/Primitive/ring.obj
+Paths=/Content/Mesh/Primitive/sphere.obj
+Paths=/Content/Mesh/Primitive/triangle.obj